spring:
  cloud:
    gateway:
      mvc:
        routes:
        - id: services-user
          uri: lb://services-user
          predicates:
            - Path=/**
          filters:
            - StripPrefix=0